/* A single, concrete client story. No generic document renderer or extra exercise. */
(() => {
 'use strict';
 const image='bram-workshop-vessel-v1.png';
 const link='<a class="br-pdf" href="havenmeer-request-dossier.pdf" download>Download the 3-page dossier ↓</a>';
 const arrow='<span aria-hidden="true">→</span>';
 const head=(step,title)=>`<header class="br-heading"><span class="eyebrow">${step}</span><h2>${title}</h2></header>`;
 const foot=t=>`<p class="br-note">${t}</p>`;
 const page=(name,body,cls='')=>`<section class="bram-request ${cls}" aria-label="${name}">${body}</section>`;
 const route=(at)=>`<ol class="br-route" aria-label="Request timeline">${['Bram asks','Planning clarifies','Bram returns','Company reviews'].map((t,i)=>`<li class="${at===i?'current':i<at?'done':''}"><span>${i+1}</span>${t}</li>`).join('')}</ol>`;
 const drawing=(small=false)=>`<svg class="br-vessel-plan ${small?'small':''}" viewBox="0 0 620 160" role="img" aria-label="Vessel side elevation: weld 7 and weld 8 go around the shell. Diameter 1200 millimetres, wall thickness 12 millimetres."><defs><linearGradient id="br-steel" x2="0" y2="1"><stop stop-color="#d7e3df"/><stop offset=".4" stop-color="#f4f7f2"/><stop offset="1" stop-color="#a6bbb4"/></linearGradient></defs><path d="M115 46H480Q532 46 532 89T480 132H115Q62 132 62 89T115 46Z" fill="url(#br-steel)" stroke="#597c72" stroke-width="2"/><path d="M220 47V131M377 47V131" fill="none" stroke="#b7802e" stroke-width="5"/><path d="M136 132v19h32v-19m270 0v19h32v-19" fill="#52786e"/><g font-family="inherit" fill="#254e46" text-anchor="middle" font-size="20"><text x="220" y="26">Weld 7</text><text x="377" y="26">Weld 8</text></g><path d="M220 30v13m157-13v13M564 46v86m-6-86h12m-12 86h12" stroke="#52786e" stroke-width="2"/><text transform="translate(599 93) rotate(-90)" text-anchor="middle" font-size="17" fill="#46675d">Ø 1,200 mm</text></svg>`;
 function workshop(b,detail){
  const labels=detail?`<svg class="br-weld-overlay" viewBox="0 0 1672 941" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g fill="none" stroke="#efc36b" stroke-width="7"><path d="M580 290Q470 440 538 607"/><path d="M1040 231Q866 404 1029 632"/></g><g stroke="#fffdf4" stroke-width="3"><path d="M654 380l-110 25M1114 365l-130 34"/></g><g fill="#fffdf4"><rect x="644" y="328" width="222" height="70" rx="15"/><rect x="1104" y="313" width="222" height="70" rx="15"/></g><g font-size="43" font-family="inherit" fill="#28554f" text-anchor="middle"><text x="755" y="376">Weld 7</text><text x="1215" y="361">Weld 8</text></g></svg>`:'';
  return page(detail?'The vessel and its welds':'Bram at Havenmeer',head('Havenmeer Process Works · Workshop 2',detail?'Two welds, one fixed vessel':'Meet Bram, our client’s contact')+`<figure class="br-workshop"><img src="${image}" alt="Illustrated industrial hall: a horizontal steel vessel anchored to supports, connected pipework and workbenches around it.">${labels}</figure>`+(detail?`<div class="br-measures"><div><small>Diameter</small><strong>1.2 m <em>· 1,200 mm</em></strong></div><div><small>Steel wall</small><strong>12 mm thick</strong></div></div>`:`<div class="br-company-line"><div><strong>Havenmeer</strong><small>Client · runs this workshop</small></div>${arrow}<div><strong>Our NDT company</strong><small>Plans and performs the inspection</small></div></div>`)+foot(detail?(b>=3?'Fixed to supports and pipework · location still to be assessed.':'A weld joins the steel sections. These two welds go all the way around.'):'Bram · maintenance manager at Havenmeer'));
 }
 function mail(b){
  return page('Bram sends the first email',head('Tuesday · 09:19','A request arrives in planning')+route(0)+`<article class="br-mail"><div class="br-mail-bar"><span class="br-avatar">B</span><div><strong>Bram · Havenmeer Process Works</strong><small>To: Our NDT planning desk</small></div></div><h3>Radiography request · two vessel welds</h3><div class="br-mail-body"><p>Good morning,</p><p>We need two welds on our steel vessel inspected by radiography. Could you fit this into your planning for Thursday?</p><p>The vessel is installed in our workshop.</p><p>Kind regards,<br><strong>Bram</strong><br><small>Maintenance manager</small></p></div></article>`+foot(b>=1?'Enquiry received · inspection details still needed.':'Bram starts the conversation. Planning will now clarify the job.'));
 }
 function reply(b){
  return page('Planning asks for the missing information',head('Tuesday · Planning replies','“Please send us the job details.”')+`<article class="br-mail br-reply"><div class="br-mail-bar"><span class="br-avatar">P</span><div><strong>Our NDT planning desk</strong><small>To: Bram · Havenmeer</small></div></div><div class="br-request-questions"><section class="${b<=1?'focus':''}"><span>01</span><div><h3>What must we examine?</h3><p>Marked weld drawing · extent of examination<br>Material · diameter · wall thickness</p></div></section><section class="${b===2?'focus':''}"><span>02</span><div><h3>Where, when and with whom?</h3><p>Exact location · proposed time · nearby work<br>Contact reachable throughout the inspection</p></div></section><section class="${b>=3?'focus':''}"><span>03</span><div><h3>Which requirements apply?</h3><p>Examination requirements and supporting documents</p></div></section></div><div class="br-attachment">↗ Inspection request form · sent to Bram</div></article>`+foot('The proposed date remains subject to preparation and review.'));
 }
 function request(b){
  return page('The completed inspection request','<header class="br-heading br-compact-heading"><span class="eyebrow">Bram returns the details · request + drawing</span></header>'+`<article class="br-paper"><div class="br-paper-top"><div><span>HAVENMEER</span><h3>Inspection request</h3></div><small>HM–RT–026<br>Requested: Thursday</small></div><div class="br-two-fields"><div><small>Client / location</small><strong>Havenmeer · Workshop 2</strong></div><div><small>Contact</small><strong>Bram · Maintenance</strong></div></div>${drawing(true)}<table class="br-weld-table"><caption>Steel vessel · drawing V2-GA, rev C</caption><thead><tr><th>Weld</th><th>Material</th><th>Diameter</th><th>Wall</th><th>Extent</th></tr></thead><tbody><tr class="${b===1?'focus':''}"><th>7 <small>W-07</small></th><td>Carbon steel</td><td>1,200 mm</td><td>12 mm</td><td>100%</td></tr><tr class="${b===1?'focus':''}"><th>8 <small>W-08</small></th><td>Carbon steel</td><td>1,200 mm</td><td>12 mm</td><td>100%</td></tr></tbody></table><div class="br-form-footer">${b>=4?'Written job information: at least 24 hours before the work.':b>=3?'Bram is reachable throughout the work.':'100% = the full circumference of each weld.'}</div></article>`);
 }
 function justification(b){
  return page('Planning sends the justification form',head('Planning → Bram','A second form asks for the reasons')+`<div class="br-form-spread"><article class="br-paper"><div class="br-paper-top"><div><span>PREPARATION · HM–RT–026</span><h3>Radiography justification</h3></div></div><div class="br-form-section"><span>01 · Technique</span><h4>Why radiography for this assignment?</h4><div class="br-writing-lines" aria-label="Field awaiting client explanation"></div></div><div class="br-form-section"><span>02 · Location</span><h4>Why the proposed location?</h4><div class="br-writing-lines" aria-label="Field awaiting client explanation"></div></div><div class="br-form-footer">Supporting assessment / reference: to be attached</div></article><aside><span class="br-tag">To be completed by the client</span><h3>Bram gathers the supporting information.</h3><p>With colleagues who have the necessary technical knowledge.</p><div class="br-next">We examine the justification next.</div></aside></div>`+link);
 }
 function tra(b){
  return page('Task risk analysis for the workshop',head('Preparation · a separate purpose','What could go wrong during the work?')+`<article class="br-paper br-tra"><div class="br-paper-top"><div><span>HAVENMEER + NDT COMPANY</span><h3>Task risk analysis · TRA</h3></div><small>Workshop 2<br>Coordination open</small></div><table><thead><tr><th>Task / situation</th><th>Hazard to assess</th><th>Coordination required</th></tr></thead><tbody><tr class="${b===1?'focus':''}"><th>Equipment setup</th><td>Forklifts pass the vessel.</td><td>Agree how traffic will be separated from the work.</td></tr><tr class="${b===1?'focus':''}"><th>Nearby workbenches</th><td>Other people may approach.</td><td>Agree who stops nearby work and controls access.</td></tr><tr class="${b>=2?'focus':''}"><th>Radiography</th><td>Exposure to ionising radiation.</td><td>NDT company assesses radiation risks and protective measures.</td></tr></tbody></table><div class="br-form-footer">Participants · Bram / client safety team / NDT company</div></article>`+foot('TRA: hazards during the task. Justification: reasons for choosing radiography.')+link);
 }
 function returned(b){
  return page('The file reaches technical and safety review',head('Bram → Planning → Review','An enquiry becomes a file to assess')+route(b<1?2:3)+`<article class="br-mail"><div class="br-mail-bar"><span class="br-avatar">B</span><div><strong>Bram · Reply to planning</strong><small>Subject: Vessel inspection · requested information</small></div></div><div class="br-return"><div><span class="br-file-mark">01</span><strong>Inspection request</strong><small>Job details + weld drawing</small></div><div><span class="br-file-mark">02</span><strong>Justification</strong><small>Reasons + supporting information</small></div><div><span class="br-file-mark">03</span><strong>Risk information</strong><small>Site hazards + coordination</small></div></div><div class="br-review-state">Technical and safety review required</div></article>`+foot('File received does not mean permission to start an exposure.')+link);
 }
 function render(cue,beat){const p=+cue.split('-P')[1];switch(p){case 1:return workshop(beat,false);case 2:return workshop(beat,true);case 3:return mail(beat);case 4:return reply(beat);case 5:return request(beat);case 6:return justification(beat);case 7:return tra(beat);default:return returned(beat);}}
 window.BramRequest={render};
})();
