/* Scene 7 only: written reasoning, location hierarchy and the resulting protection. */
(() => {
 'use strict';
 const law='https://www.jurion.fanc.fgov.be/jurdb-consult/plainWettekstServlet?lang=nl&wettekstId=32765';
 const definitions='https://www.jurion.fanc.fgov.be/jurdb-consult/plainWettekstServlet?lang=nl&wettekstId=32766';
 const refs={
  overview:['Articles 3–5 & 7','Three justification responsibilities','The client provides written justification of the NDT technique and location for each type of assignment. The NDT company justifies its equipment choice and evaluates acceptance. A licence does not remove these assignment requirements.'],
  technique:['Article 3','Why use radiography?','A specific industrial standard issued by a recognised standardisation organisation may require radiography for the assignment type. Where the client demands more than the applicable standard, or a standard does not provide for RT, the client demonstrates justification through a risk analysis considering undetected fabrication defects. The justification is provided in writing.'],
  threshold:['Article 4 §3; Article 7 §1','When the bunker is mandatory','The rule applies to movable complete workpieces that fit within one cubic metre AND weigh less than 500 kg. It is not an either/or test, and not a test of weld size alone. Larger or heavier workpieces are still preferably examined in a bunker under Article 4 §4. The NDT company checks the bunker’s valid conformity certificate.'],
  hierarchy:['Article 4 §§1–5; Articles 2 & 18','The order of location assessment','First assess the bunker. If radiography of larger/heavier pieces is not reasonably feasible there, an irradiation infrastructure at the client’s site may be used after both parties’ risk analyses. Only if neither option is reasonably feasible may another place be considered after both analyses. An irradiation infrastructure has fixed shielding; the required arrangements include entrance supervision.'],
  bram:['Article 4 §§1–5; Article 7 §2','Applying the rule to Bram’s vessel','Immobility explains why transport is examined; it does not automatically justify radiography in the hall. The client must provide a supported written assessment of the location, including both preferred options and its risk information. The NDT company performs its risk analysis and reviews acceptance. The fictional case is not a site authorisation.'],
  perimeter:['Articles 8, 16 & 19 §§1, 6–9','A continuous, supervised perimeter','Before exposure: a continuous boundary with at least barrier tape and radiation warning signs; a warning lamp in darkness or poor visibility. Inform the client’s contact and agree adequate supervision, adding personnel where necessary. At least two industrial radiographers work outside a bunker. Entry during exposure is restricted by Article 19 §8; ordinary workshop staff stay outside. Active measurement is also required on approach after exposure or at completion.'],
  measurements:['Article 19 §§2–5','Verifying the boundary','For radiographic exposure, maximum rates outside the perimeter depend on occupancy: 10 µSv/h for permanent workplaces and adjoining buildings; 40 µSv/h for non-permanent workplaces. Work at the same place is limited to keep each non-occupationally exposed person’s dose at or below 300 µSv/year. Measure actively at the edge during the first or a test exposure; enlarge the perimeter as necessary. These maxima do not replace optimisation. Article 19 §4 separately addresses brief gamma-source transit, which must be as fast as possible.'],
  equipment:['Articles 5 & 7 §2','Equipment justification and acceptance','X-ray equipment is preferred where feasible without additional risk. If gamma is used, the isotope’s penetrating power must suit the examination. The head of physical control ensures competent justification of technique, isotope and activity. The NDT company refuses the assignment if it does not accept the Article 3 or 4 justification.'],
  review:['Articles 7 §2, 11 §2 & 16','Review before work; stop if unsafe','The written justification and accepted location do not replace operational preparation. Required risk-control measures must be present and an LMRA is performed. Radiographers stop when they cannot work safely, and immediately report the reason to their hierarchy, the head of physical control and the client’s contact.']
 };
 const ref=id=>`<footer class="jp-source"><span>Belgian Royal Decree · 17 February 2023</span><button type="button" data-jp-source="${id}" aria-label="Read legal basis: ${refs[id][0]}">${refs[id][0]} ↗</button></footer>`;
 const frame=(title,eyebrow,body,source)=>`<section class="jp-explainer" aria-label="${title}"><header class="jp-heading"><span>${eyebrow}</span><h2>${title}</h2></header>${body}${ref(source)}</section>`;
 const focus=t=>`<div class="jp-focus">${t}</div>`;
 const active=(x,b)=>x===b?' is-active':'';
 const workshop='<img class="jp-workshop" src="bram-workshop-vessel-v1.png" alt="Bram’s installed vessel in the Havenmeer workshop">';
 const bunker=()=>`<div class="jp-bunker" role="img" aria-label="Company bunker with roof, shielded door and external control position">${BunkerArt.svg.company}</div>`;
 const vessel='<rect x="174" y="130" width="212" height="82" rx="40" fill="#cbdcd1" stroke="#658976" stroke-width="2"/><path d="M238 132v78m81-78v78" stroke="#b99854" stroke-width="4"/><text x="280" y="178" text-anchor="middle" font-size="18" fill="#325948">Vessel</text>';
 function infrastructure(){return `<svg class="jp-diagram" viewBox="0 0 550 320" role="img" aria-label="Fixed radiation shielding around an inspection area, with a supervised entrance and external controls"><rect x="18" y="22" width="512" height="275" rx="10" fill="#edf0e6"/><path d="M100 270V63H460V270H354m-82 0H100" fill="none" stroke="#82998a" stroke-width="20"/>${vessel}<path d="M272 270v-53h81" fill="none" stroke="#b79451" stroke-width="3"/><rect x="39" y="192" width="36" height="40" rx="5" fill="#476e5c"/><text x="278" y="38" text-anchor="middle" font-size="18" fill="#446b57">Fixed shielding</text><text x="328" y="307" text-anchor="middle" font-size="16" fill="#446b57">Supervised entrance</text><text x="56" y="254" text-anchor="middle" font-size="14" fill="#446b57">Controls</text></svg>`;}
 function perimeter(b){return `<svg class="jp-diagram" viewBox="0 0 560 340" role="img" aria-label="Conceptual workshop plan: a continuous protective perimeter around the vessel, two supervised entry routes, and nearby workstations outside. Distances require a job assessment."><defs><pattern id="jp-tape" width="18" height="18" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><rect width="18" height="18" fill="#efd784"/><rect width="8" height="18" fill="#726b4d"/></pattern></defs><rect x="12" y="15" width="536" height="300" rx="10" fill="#eef0e7" stroke="#b3c5b2"/><g fill="#c9d8ca" stroke="#92a994"><rect x="421" y="37" width="107" height="31" rx="4"/><rect x="420" y="105" width="108" height="31" rx="4"/></g><text x="475" y="91" text-anchor="middle" font-size="15" fill="#46624f">Workbenches</text><rect x="76" y="57" width="328" height="218" rx="17" fill="#f2dd9b22" stroke="url(#jp-tape)" stroke-width="7"/>${vessel.replace('174','133').replace('386','345').replace('238','197').replace('319','278').replace('280','239')}<text x="244" y="246" text-anchor="middle" font-size="15" fill="#786239">Protected area</text><g class="${b===1?'jp-glow':''}" transform="translate(67 90)"><path d="M0 27 18 0 36 27Z" fill="#f0cc5b" stroke="#80643b" stroke-width="2"/><text x="18" y="22" text-anchor="middle" font-size="21" fill="#262a24">☢</text></g><path d="M26 313h53m360 0h99" stroke="#819a85" stroke-width="6"/><g fill="#3e7662"><circle cx="58" cy="285" r="17"/><circle cx="420" cy="284" r="17"/></g><g fill="#fff" font-size="16" text-anchor="middle"><text x="58" y="291">A</text><text x="420" y="290">B</text></g><g font-size="14" fill="#45654f"><text x="27" y="335">Entry route A</text><text x="379" y="335">Entry route B</text></g>${b>=2?'<path d="M59 305v-46m360 46v-46" stroke="#ae7945" stroke-width="4"/>':''}</svg>`;}
 function render(cue,b){let p=+cue.split('-P')[1];
  if(p===1)return frame('Three questions before accepting the job','Bram’s request · who provides the reasoning?',`<div class="jp-split"><div>${workshop}<p class="jp-caption">Havenmeer Process Works · welds 7 and 8</p></div><div class="jp-roles"><article class="${active(1,b)}"><span>CLIENT · HAVENMEER</span><h3>Why radiography?</h3><h3>Why this location?</h3><p>Written justification</p></article><article class="${active(2,b)}"><span>OUR NDT COMPANY</span><h3>Why this equipment?</h3><p>Assessment and acceptance</p></article></div></div>`,'overview');
  if(p===2)return frame('Why is radiography required here?','Technique justification · the client’s responsibility',`<div class="jp-routes"><article class="${active(1,b)}"><span class="jp-number">01</span><h3>Industrial standard requires RT</h3><p>Recognised standardisation organisation</p><div class="jp-line">Identify the requirement that applies.</div></article><article class="${active(2,b)}"><span class="jp-number">02</span><h3>Client demonstrates justification</h3><p>No RT requirement in a standard, or higher client demands</p><div class="jp-line">Risk analysis: consequences of missed defects</div></article></div>`+focus(b>=3?'An order or a technique standard alone does not establish the reason for RT.':'Two routes to a supported written justification.'),'technique');
  if(p===3)return frame('Bram’s file follows the second route','The pressure-retaining welds · examine the supporting evidence',`<div class="jp-two-files"><article class="jp-file ${b<2?'is-active':''}"><span>TECHNIQUE JUSTIFICATION</span><h3>What if a weld defect is missed?</h3><p>Consequences for the vessel</p><p>Required inspection information</p><p>Suitable alternative techniques</p></article><article class="jp-file ${b>=2?'is-active':''}"><span>TASK RISK ASSESSMENT</span><h3>What could go wrong at work?</h3><p>Crane movements and access</p><p>Nearby work and occupancy</p><p>Measures for this workshop</p></article></div>`+focus('Project requirement → reasoned risk analysis → NDT company review'),'technique');
  if(p===4)return frame('This small movable assembly goes to the bunker','Location · the mandatory rule',`<div class="jp-threshold"><div class="jp-smallpiece"><svg viewBox="0 0 310 220" role="img" aria-label="Separate small pipe assembly inside a one-metre cube; example dimensions eighty by sixty by forty centimetres"><path d="M51 71 156 23 270 80 160 138Z" fill="#e4eee5" stroke="#7b9b88" stroke-dasharray="5 5"/><path d="M51 71v108l109 39V138m0 80 110-60V80" fill="none" stroke="#7b9b88" stroke-dasharray="5 5"/><path d="M156 23v116" stroke="#b9cbbd" stroke-dasharray="5 5"/><path d="M97 130h68v-39h62" fill="none" stroke="#829c8e" stroke-width="27" stroke-linejoin="round"/><path d="M96 122h61v-39h68" fill="none" stroke="#cbd8ce" stroke-width="11"/><text x="28" y="42" font-size="16" fill="#426a55">1 m</text></svg><p>80 × 60 × 40 cm · 120 kg</p><span>Separate movable pipe assembly</span></div><div class="jp-rule"><div class="${active(0,b)}">Movable complete workpiece</div><div class="${active(1,b)}">Fits within <strong>1 m³</strong></div><b class="jp-and">AND</b><div class="${active(2,b)}">Mass <strong>&lt; 500 kg</strong></div><p class="jp-required">BUNKER REQUIRED</p></div><div class="jp-mini-bunker">${bunker()}</div></div>`+focus(b>=5?'The rule concerns the complete workpiece, not the weld length.':'All three conditions apply together.'),'threshold');
  if(p===5){const tier=b<1?0:b<3?1:2;return frame('Larger or heavier? Follow the location order','Reasonable feasibility · not a free choice',`<div class="jp-hierarchy"><ol><li class="${active(0,tier)}"><b>1</b><div><h3>Bunker</h3><p>Still the preferred location</p></div></li><li class="${active(1,tier)}"><b>2</b><div><h3>Irradiation infrastructure</h3><p>If bunker use is not reasonably feasible</p></div></li><li class="${active(2,tier)}"><b>3</b><div><h3>Another location</h3><p>Only if neither option is reasonably feasible</p></div></li></ol><div class="jp-location-art">${tier===0?bunker():tier===1?infrastructure():workshop}</div></div>`+focus(tier===0?'The small-workpiece rule remains mandatory.':tier===1?'Fixed shielding + required safety arrangements. Barrier tape is not infrastructure.':'Written justification + risk analyses by client and NDT company.'),'hierarchy');}
  if(p===6)return frame('The welds cannot travel separately','Bram’s installed vessel · diameter 1.2 m',`<div class="jp-split"><div class="jp-vessel-photo">${workshop}<div>Weld 7 &nbsp; · &nbsp; Weld 8</div></div><div class="jp-assessments"><article class="${active(1,b)}"><span>FIRST ASSESSMENT</span><h3>Dismantle and transport?</h3><p>Record why bunker use is not reasonably feasible.</p></article><article class="${active(2,b)}"><span>SECOND ASSESSMENT</span><h3>Provide fixed shielding here?</h3><p>Assess infrastructure feasibility, not only its absence.</p></article></div></div>`+focus(b>=3?'“We have none” is insufficient. Reasons and both risk analyses are needed.':'The installed vessel is the workpiece. Two short welds do not make it movable.'),'bram');
  if(p===7){const line=b<1?['Continuous boundary','Tape marks the area; it does not shield radiation.']:b===1?['Clear warning','Radiation signs; warning lamp in poor visibility.']:b===2?['All routes considered','Doors, benches and other access into the work area.']:['Supervision agreed','Coverage by the team, with extra personnel when needed.'];return frame('A justified hall still needs a protected work area','Outside a bunker or irradiation infrastructure',`<div class="jp-plan-layout">${perimeter(b)}<div class="jp-plan-copy"><h3>${line[0]}</h3><p>${line[1]}</p><div class="jp-mini-note">Inform Bram of the perimeter.<br>At least two radiographers outside a bunker.</div></div></div>`+focus('Plan, mark, communicate and supervise. No fixed distance can be read from this sketch.'),'perimeter');}
  if(p===8)return frame('Measure the boundary; adjust it if needed','Perimeter limits · occupancy matters',`<div class="jp-rates"><article class="${active(0,b)}"><strong>10 <small>µSv/h</small></strong><h3>Permanent workstations</h3><p>And adjoining buildings</p></article><article class="${active(1,b)}"><strong>40 <small>µSv/h</small></strong><h3>Non-permanent workstations</h3><p>During radiographic exposure</p></article></div><div class="jp-annual ${active(2,b)}"><strong>300 µSv/year</strong><span>Per non-occupationally exposed person<br>from radiography at the same place</span></div><div class="jp-measure ${b>=3?'is-active':''}"><span>First / test exposure</span><b>→</b><span>Active measurement at the edge</span><b>→</b><span>Enlarge if necessary</span></div>`+focus('Maximum constraints, not targets. Optimisation continues below them.'),'measurements');
  if(p===9)return frame('Our company justifies the equipment','The third question · competent assessment',`<div class="jp-equipment"><figure class="${b<1?'is-active':''}"><img src="xray.png" alt="X-ray generator"><figcaption><strong>X-ray generator</strong><span>Preferred where feasible without extra risk</span></figcaption></figure><figure class="${b===1?'is-active':''}"><img src="gamma.png" alt="Gamma projector"><figcaption><strong>Gamma projector</strong><span>Penetrating power suited to the examination</span></figcaption></figure></div>`+focus(b>=3?'Technique or location justification not accepted → ASSIGNMENT REFUSED':'Head of physical control: competent justification of technique, isotope and activity.'),'equipment');
  return frame('A connected file before work starts','Bram’s request · from reasoning to preparation',`<div class="jp-final"><div class="jp-evidence"><h3>Evidence to review</h3><p>Why radiography</p><p>Why this location</p><p>Why this equipment</p><p>Agreed protection arrangements</p></div><div class="jp-final-step ${b>=2?'is-active':''}"><span>AT THE WORKPLACE</span><h3>Measures in place + LMRA</h3><p>If safe working is impossible:</p><strong>STOP AND REPORT</strong></div></div>`+focus(b>=5?'Wall thickness is not a threshold in the small-workpiece bunker rule.':'Your turn · place three workpieces using the size, weight and feasibility information.'),'review');
 }
 function openSource(id){const r=refs[id];if(!r)return;Player.reader(r[1],`<article class="jp-source-reader"><p class="jp-reader-kind">Legislation · Royal Decree of 17 February 2023 on industrial radiography</p><h3>${r[0]}</h3><p>${r[2]}</p><p><a href="${law}" target="_blank" rel="noreferrer">Read the official legal text in FANC Jurion (Dutch) ↗</a></p>${id==='hierarchy'?`<p><a href="${definitions}" target="_blank" rel="noreferrer">Read the legal definitions in Article 2 ↗</a></p>`:''}<p class="jp-reader-kind">Course explanation in English; the linked legal text is the source. Checked 6 October 2026.</p></article>`);}
 window.JustificationPath={render,openSource};
})();
